### ISSUE TITLE
QModManager has stopped working

### ISSUE THREAD

**Issue by bmcminn** [oldark87/GraveyardKeeper#1]
Still need to dig a bit further, but just followed the instructions per https://www.nexusmods.com/graveyardkeeper/mods/1?tab=description

Just ran a few system updates, so starting from system bootup here.

1. Open the installer
2. Installer pulls up the correct Graveyard Keeper file path
3. Click install
4. System error prompt pops up citing "QModManager has stopped working: A problem caused the program to stop working correctly."

Will attempt to uninstall QModManager and try again, but seeing if anyone else has had issues?

Windows 7 Pro SP1 64bit
Intel i7-4820K

**Comment by kylinator25** [comment]
Support for the Graveyard Keeper branch of QMods doesn't exist, sorry but the installer was last updated in *January* dude.

**Comment by oldark87** [comment]
Hey bmcminn, thank you for the report!  While I'm not actively supporting updates on this anymore I will look into it. Did reinstalling work? A reinstall should be done after every game update and a user posted recently on the nexusmod page for this that reinstalling it cleared the issue for them.

**Comment by bmcminn** [comment]
@oldark87 well that's fun, just tried uninstalling it and hit a similar problem.

Got a debugger statement to pull up:

```
System.IO.DirectoryNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in mscorlib.dll
Additional information: Could not find a part of the path 'D:\apps\Steam\steamapps\common\Graveyard Keeper\output_log.txt'.
```

Was able to at least create that file and got it to resolve. Attempting a reinstall now
